### ISSUE TITLE
Problemas em exibir as tarefas

### ISSUE THREAD

**Issue by Pakato14** [InFog/phpmysql#2]
Olá, comprei seu livro Desenvolvimento Web com PHP e MySQL da casa do código e estou com problemas em exibir as tarefas armazenadas no banco, estou seguindo passo a passo, o sistema está conseguindo gravar e o problema é quando acesso a página tarefas.php, ele não mostra as tarefas armazenadas, poderia verificar em que estou errando? segue abaixo o link do git hub.

https://github.com/Pakato14/Tarefa

**Comment by InFog** [comment]
Olá, @Pakato14. Você habilitou os erros no PHP? Consegue ver algum erro gerado na hora de exibir a página?

**Comment by Pakato14** [comment]
Estão habilitados, o formulário aparece normal, grava no banco de dados, mas não aparece no navegador

![image](https://user-images.githubusercontent.com/17130546/30030012-e1afcd9c-9161-11e7-8ddc-d3bfe2c9516a.png)

**Comment by InFog** [comment]
Já vi o problema, você precisa mover o `require "template.php";` para o final do arquivo `tarefas.php`. Assim a variável `$lista_tarefas` vai existir.

**Comment by marinhoneto** [comment]
Ola InFog, estou com o mesmo problema. Como pode me ajudar?

**Comment by InFog** [comment]
O que voce já fez, @marinhoneto ?

**Comment by marinhoneto** [comment]
Onde eu errei???
Segue os códigos abaixo...

**Banco.php**
<?php

	$bdServidor = "localhost";
	$bdPorta = 8889;
	$bdUsuario = "sistematarefas";
	$bdSenha = "sistema";
	$bdBanco = "tarefas";
	//$link = mysqli_init();

	$conexao = mysqli_connect('p:'.$bdServidor, $bdUsuario, $bdSenha, $bdBanco, $bdPorta);

	if (mysqli_connect_errno($conexao)) {
		echo "Problemas para conectar no banco. Verifique os dados! \n";
		echo "Conectado ao Banco de Dados: " . $bdBanco;
		echo " Usuário: " . $bdUsuario;
		echo "Error: Unable to connect to MySQL." . PHP_EOL;
		echo "Debugging errno: " . mysqli_connect_errno() . PHP_EOL;
		echo "Debugging error: " . mysqli_connect_error() . PHP_EOL;
		die(mysqli_error());
	} else {
		echo "Conexão OK! ";
		echo "Conectado ao Banco de Dados: " . $bdBanco;
		echo " Usuário: " . $bdUsuario;
	}

	function buscar_tarefas($conexao)
	{
		$sqlBusca = 'SELECT * FROM tarefas';
		$resultado = mysqli_query($conexao, $sqlBusca);

		  $tarefas = array();

		  //false !==
		  while ($tarefa = mysqli_fetch_assoc($resultado)) {
			 $tarefas[] = $tarefa;
		  }

		return $tarefas;
	}

	function gravar_tarefa($conexao, $tarefa)
	{
		$sqlGravar = "
			INSERT INTO tarefas
			(nome, descricao, prioridade)
			VALUES
			(
				'{$tarefa['nome']}',
				'{$tarefa['descricao']}',
				'{$tarefa['prioridade']}'
			)
		";

		mysqli_query($conexao, $sqlGravar);
	}

?>
-----------------------------------------------------------------------------------------------------
**Tarefas.php**
<?php
	session_start();

	require 'banco.php';
	require 'ajudantes.php';

	$tarefa = array();

	if (isset($_GET['nome']) && $_GET['nome'] != '') {
		//$tarefa = array();

		$tarefa['nome'] = $_GET['nome'];

		if (isset($_GET['descricao'])) {
			$tarefa['descricao'] = $_GET['descricao'];
		} else {
			$tarefa['descricao'] = '';
		}

		if (isset($_GET['prazo'])) {
			$tarefa['prazo'] = $_GET['prazo'];
		} else {
			$tarefa['prazo'] = '';
		}

		$tarefa['prioridade'] = $_GET['prioridade'];

		if (isset($_GET['concluida'])) {
			$tarefa['concluida'] = $_GET['concluida'];
		} else {
			$tarefa['concluida'] = '';
		}

		/*O codigo abaixo servia para pegar os dados
		do array e jogar na sessao da pagina*/
		//$_SESSION['lista_tarefas'][] = $tarefa;

		//O codigo abaixo serve para jogar os dados do array no Banco de Dados
		//$conexao = null;
        gravar_tarefa($conexao, $tarefa);
	}

	//$lista_tarefas = array();

	$lista_tarefas = buscar_tarefas($conexao);

	$tarefa = array(
		'id' => 0,
		'nome' =>'',
		'discricao' =>'',
		'prazo' =>'',
		'prioridade' =>'1',
		'concluida' =>''
	);

	require 'template.php';
?>
--------------------------------------------------------------------------------------------------------------
**Template.php**
<html>
    <head>
        <meta charset="utf-8" />
        <title>Gerenciador de Tarefas</title>
        <link rel="stylesheet" href="tarefas.css" type="text/css" />
    </head>
<body>
	<h1>Gerenciador de Tarefas</h1>
	<form>
		<fieldset>
			<legend>Nova Tarefa</legend>
			<label>
				Tarefa:
				<input type="text" name="nome">
			</label>
			<label>
				Descrição (Opcional):
				<textarea name="descricao"></textarea>
			</label>
			<label>
				Prazo (Opcional):
				<input type="text" name="prazo">
			</label>
			<fieldset>
				<legend>Prioridade:</legend>
				<label>
					<input type="radio" name="prioridade" value="1" checked />
					Baixa
					<input type="radio" name="prioridade" value="2" />
					Média
					<input type="radio" name="prioridade" value="3" />
					Alta
				</label>
			</fieldset>
			<label>
				Tarefa Concluída:
				<input type="checkbox" name="concluida" value="sim">
			</label>
			<input type="submit" value="Cadastrar">
		</fieldset>
	</form>
	<table border="1">
		<tr>
			<th>Tarefas</th>
			<th>Descrição</th>
			<th>Prazo</th>
			<th>Prioridade</th>
			<th>Concluída</th>
		</tr>
		<?php foreach ($lista_tarefas as $tarefa) : ?>
			<tr>
				<td><?php echo $tarefa['nome']; ?></td>
				<td><?php echo $tarefa['descricao']; ?></td>
				<td><?php echo $tarefa['prazo']; ?></td>
				<td><?php echo traduz_prioridade($tarefa['prioridade']); ?></td>
				<td><?php echo $tarefa['concluida']; ?></td>
			</tr>
		<?php endforeach; ?>
	</table>
</body>
</html>
--------------------------------------------------------------------------------------------------------------
**ajudantes.php**
<?php

function traduz_prioriadae($codigo)
{
	$prioridade = '';
	switch ($codigo) {
		case '1':
			$prioridade = 'Baixa';
			break;
		case '2':
			$prioridade = "Média";
			break;
		case '3':
			$prioridade = "Alta";
			break;
	}

	return $prioridade;
}

?>
